Homework 4
React-js-Developer-MySklad/homework-mkniazev pull request #5
Opened 2024-08-22 17:06 UTC by knzv-dev

2024-08-22 17:10 UTC, knzv-dev commented
[Screencast from 22.08.2024 22:08:45.webm](https://github.com/user-attachments/assets/be015299-ae7d-4d89-921f-462aef6c87a0)

2024-09-01 08:17 UTC, koshelnikov requested changes
Максим, вам нужно обернуть код в провайдер. Сейчас данная версия это просто модуль, который через функцию получает доступ к другой функции.

Посмотрите пример в lesson-14 AuthenticationProvider

2024-09-02 08:58 UTC, knzv-dev commented
Исправил

2024-09-08 18:39 UTC, koshelnikov approved these changes

2024-09-08 18:39 UTC, merged